### ISSUE TITLE
Revisit the rate-limit set for the calico manifest download

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/k8s-ansible#27]
We have introduced the `rate-limit` for the calico manifest download via https://github.com/ppc64le-cloud/k8s-ansible/pull/13, but this is creating a bottleneck and adding more time to the overall installation. This needs to be revisited and explore if there is a scope of removing this open or increasing the limit to the higher value.

/assign @Rajalakshmi-Girish

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag while we added the `--limit-rate=1k ` even an increase to 2k was throwing download error.
I shall retry and see if there is scope for removal/increase.

**Comment by mkumatag** [comment]
I tried this on one of the powervs vm and see it finishes within a 2sec without any issues:

```shell
[root@mkumatag-workspace ~]# curl -O https://docs.projectcalico.org/manifests/calico.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  197k  100  197k    0     0  97703      0  0:00:02  0:00:02 --:--:-- 97703
[root@mkumatag-workspace ~]#
```

Lets explore and see if it still happening, if yes - we can take help from n/w team to debug further.

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> I tried this on one of the powervs vm and see it finishes within a 2sec without any issues:
> 
> ```shell
> [root@mkumatag-workspace ~]# curl -O https://docs.projectcalico.org/manifests/calico.yaml
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  197k  100  197k    0     0  97703      0  0:00:02  0:00:02 --:--:-- 97703
> [root@mkumatag-workspace ~]#
> ```
> 
> Lets explore and see if it still happening, if yes - we can take help from n/w team to debug further.

There is no Error even without limiting the download rate. I checked on a new VM created now in osa21.
@mkumatag Shall I revert to old task by removing the `--limit-rate` ?

**Comment by mkumatag** [comment]
> > I tried this on one of the powervs vm and see it finishes within a 2sec without any issues:
> > ```shell
> > [root@mkumatag-workspace ~]# curl -O https://docs.projectcalico.org/manifests/calico.yaml
> >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> >                                  Dload  Upload   Total   Spent    Left  Speed
> > 100  197k  100  197k    0     0  97703      0  0:00:02  0:00:02 --:--:-- 97703
> > [root@mkumatag-workspace ~]#
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Lets explore and see if it still happening, if yes - we can take help from n/w team to debug further.
> 
> There is no Error even without limiting the download rate. I checked on a new VM created now in osa21.
> @mkumatag Shall I revert to old task by removing the `--limit-rate` ?

lets do that.

**Comment by Rajalakshmi-Girish** [comment]
Remove the limit on download rate for calico manifest - https://github.com/ppc64le-cloud/k8s-ansible/pull/28
Update Ansible submodule - https://github.com/ppc64le-cloud/kubetest2-plugins/pull/44
A successful run with changed code: https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-conformance-test-ppc64le/1432590197786152961
@mkumatag We may close this.
