### ISSUE TITLE
check if need all the kubernetes tarballs needed for install and test

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/k8s-ansible#74]
Need to check if we need all the following tarballs for our testing because some of the binaries exists in multiple of these tarballs.

https://github.com/ppc64le-cloud/k8s-ansible/blob/54bdefbd4cabbcaadef0b1018cbe94ae1740da6a/group_vars/all#L36:L38

**Comment by mkumatag** [comment]
cc @kishen-v

**Comment by kishen-v** [comment]
Completed by #73 
/close
