### ISSUE TITLE
Add Retry logic for `Extract the k8s bits`

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/k8s-ansible#9]
There are following instances and seen error downloading the k8s bits, need retry logic for this ansible step.

```
TASK [download-k8s : Extract the k8s bits] *************************************
649
failed: [128.168.101.77] (item=kubernetes-test-linux-ppc64le.tar.gz) => {"ansible_loop_var": "item", "changed": false, "item": "kubernetes-test-linux-ppc64le.tar.gz", "msg": "Failure downloading https://storage.googleapis.com/kubernetes-release-dev/ci/v1.21.0-beta.0.195+be2a2988a0c6b5/kubernetes-test-linux-ppc64le.tar.gz, HTTP Error 404: Not Found"}
650
failed: [128.168.101.77] (item=kubernetes-client-linux-ppc64le.tar.gz) => {"ansible_loop_var": "item", "changed": false, "item": "kubernetes-client-linux-ppc64le.tar.gz", "msg": "Failure downloading https://storage.googleapis.com/kubernetes-release-dev/ci/v1.21.0-beta.0.195+be2a2988a0c6b5/kubernetes-client-linux-ppc64le.tar.gz, HTTP Error 404: Not Found"}
651
failed: [128.168.101.77] (item=kubernetes-server-linux-ppc64le.tar.gz) => {"ansible_loop_var": "item", "changed": false, "item": "kubernetes-server-linux-ppc64le.tar.gz", "msg": "Failure downloading https://storage.googleapis.com/kubernetes-release-dev/ci/v1.21.0-beta.0.195+be2a2988a0c6b5/kubernetes-server-linux-ppc64le.tar.gz, HTTP Error 404: Not Found"}
652
```

/kind bug
/assign @RagniGarg97

**Comment by ltccci** [comment]
@mkumatag: The label(s) `kind/bug` cannot be applied, because the repository doesn't have them

<details>

In response to [this](https://github.com/ppc64le-cloud/k8s-ansible/issues/9):

>There are following instances and seen error downloading the k8s bits, need retry logic for this ansible step.
>
>```
>TASK [download-k8s : Extract the k8s bits] *************************************
>649
>failed: [128.168.101.77] (item=kubernetes-test-linux-ppc64le.tar.gz) => {"ansible_loop_var": "item", "changed": false, "item": "kubernetes-test-linux-ppc64le.tar.gz", "msg": "Failure downloading https://storage.googleapis.com/kubernetes-release-dev/ci/v1.21.0-beta.0.195+be2a2988a0c6b5/kubernetes-test-linux-ppc64le.tar.gz, HTTP Error 404: Not Found"}
>650
>failed: [128.168.101.77] (item=kubernetes-client-linux-ppc64le.tar.gz) => {"ansible_loop_var": "item", "changed": false, "item": "kubernetes-client-linux-ppc64le.tar.gz", "msg": "Failure downloading https://storage.googleapis.com/kubernetes-release-dev/ci/v1.21.0-beta.0.195+be2a2988a0c6b5/kubernetes-client-linux-ppc64le.tar.gz, HTTP Error 404: Not Found"}
>651
>failed: [128.168.101.77] (item=kubernetes-server-linux-ppc64le.tar.gz) => {"ansible_loop_var": "item", "changed": false, "item": "kubernetes-server-linux-ppc64le.tar.gz", "msg": "Failure downloading https://storage.googleapis.com/kubernetes-release-dev/ci/v1.21.0-beta.0.195+be2a2988a0c6b5/kubernetes-server-linux-ppc64le.tar.gz, HTTP Error 404: Not Found"}
>652
>```
>
>/kind bug
>/assign @RagniGarg97 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by RagniGarg97** [comment]
https://github.com/ppc64le-cloud/k8s-ansible/pull/11

**Comment by ltccci** [comment]
@RagniGarg97: Closing this issue.

<details>

In response to [this](https://github.com/ppc64le-cloud/k8s-ansible/issues/9#issuecomment-791154579):

>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
